using GreenCityReporter.Data;
using GreenCityReporter.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace GreenCityReporter.Controllers
{
    [Authorize]
    public class ReportController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IWebHostEnvironment _environment;
        public ReportController(
          ApplicationDbContext context,
          UserManager<ApplicationUser> userManager,
          IWebHostEnvironment environment)
        {
            _context = context;
            _userManager = userManager;
            _environment = environment;
        }

        // GET: /Report/Create
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var categories = await _context.Categories
                .OrderBy(c => c.Name)
                .ToListAsync();

            ViewBag.Categories = new SelectList(categories, "Id", "Name");

            return View();
        }

        // POST: /Report/Create
       


          [HttpPost]
          [ValidateAntiForgeryToken]
            public async Task<IActionResult> Create(Report report, IFormFile? image)
        {
            // These values are generated by the server.
            ModelState.Remove(nameof(Report.UserId));
            ModelState.Remove(nameof(Report.TrackingNumber));
            ModelState.Remove(nameof(Report.ImagePath));
            ModelState.Remove(nameof(Report.Priority));
            ModelState.Remove(nameof(Report.CurrentStatus));
            ModelState.Remove(nameof(Report.CreatedAt));
            ModelState.Remove(nameof(Report.UpdatedAt));

            if (!ModelState.IsValid)
            {
                var categories = await _context.Categories
                    .OrderBy(c => c.Name)
                    .ToListAsync();

                ViewBag.Categories = new SelectList(
                    categories,
                    "Id",
                    "Name",
                    report.CategoryId
                );

                return View(report);
            }

            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return Challenge();
            }

            // Handle image upload
            if (image != null && image.Length > 0)
            {
                // Allowed image extensions
                var allowedExtensions = new[]
                {
            ".jpg",
            ".jpeg",
            ".png",
            ".gif",
            ".webp"
        };

                var extension = Path.GetExtension(image.FileName).ToLowerInvariant();

                if (!allowedExtensions.Contains(extension))
                {
                    ModelState.AddModelError(
                        "ImagePath",
                        "Only JPG, JPEG, PNG, GIF, and WEBP images are allowed."
                    );

                    var categories = await _context.Categories
                        .OrderBy(c => c.Name)
                        .ToListAsync();

                    ViewBag.Categories = new SelectList(
                        categories,
                        "Id",
                        "Name",
                        report.CategoryId
                    );

                    return View(report);
                }

                // Maximum file size: 5 MB
                const long maxFileSize = 5 * 1024 * 1024;

                if (image.Length > maxFileSize)
                {
                    ModelState.AddModelError(
                        "ImagePath",
                        "The image size cannot exceed 5 MB."
                    );

                    var categories = await _context.Categories
                        .OrderBy(c => c.Name)
                        .ToListAsync();

                    ViewBag.Categories = new SelectList(
                        categories,
                        "Id",
                        "Name",
                        report.CategoryId
                    );

                    return View(report);
                }

                // Create upload directory
                var webRootPath = _environment.WebRootPath;

                if (string.IsNullOrEmpty(webRootPath))
                {
                    webRootPath = Path.Combine(
                        _environment.ContentRootPath,
                        "wwwroot"
                    );
                }

                var uploadFolder = Path.Combine(
                    webRootPath,
                    "uploads",
                    "reports"
                );

                if (!Directory.Exists(uploadFolder))
                {
                    Directory.CreateDirectory(uploadFolder);
                }

                // Generate a unique filename
                var fileName = $"{Guid.NewGuid()}{extension}";

                var filePath = Path.Combine(
                    uploadFolder,
                    fileName
                );

                // Save image to wwwroot/uploads/reports
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await image.CopyToAsync(stream);
                }

                // Save relative path in database
                report.ImagePath = $"/uploads/reports/{fileName}";
            }
            else
            {
                report.ImagePath = null;
            }

            // System-generated values
            report.UserId = user.Id;
            report.TrackingNumber = GenerateTrackingNumber();
            report.CurrentStatus = Models.Enums.ReportStatus.Pending;
            report.Priority = Models.Enums.Priority.Low;
            report.CreatedAt = DateTime.UtcNow;
            report.UpdatedAt = DateTime.UtcNow;

            _context.Reports.Add(report);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(MyReports));
        }



        // GET: /Report/MyReports
        [HttpGet]
        public async Task<IActionResult> MyReports()
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return Challenge();
            }

            var reports = await _context.Reports
                .Include(r => r.Category)
                .Where(r => r.UserId == user.Id)
                .OrderByDescending(r => r.CreatedAt)
                .ToListAsync();

            return View(reports);
        }

        // GET: /Report/Details/5
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return Challenge();
            }

            var report = await _context.Reports
                .Include(r => r.Category)
                .Include(r => r.Comments)
                    .ThenInclude(c => c.User)
                .Include(r => r.StatusHistories)
                    .ThenInclude(sh => sh.Updater)
                .FirstOrDefaultAsync(r => r.Id == id);

            if (report == null)
            {
                return NotFound();
            }

            // Citizens can only view their own reports.
            // Admin access will be handled separately.
            if (report.UserId != user.Id && !User.IsInRole("Admin"))
            {
                return Forbid();
            }

            return View(report);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddComment(int reportId, string message)
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return Challenge();
            }

            // Find the report
            var report = await _context.Reports
                .FirstOrDefaultAsync(r => r.Id == reportId);

            if (report == null)
            {
                return NotFound();
            }

            // Citizens can only comment on their own reports.
            // Admins can comment on any report.
            if (report.UserId != user.Id && !User.IsInRole("Admin"))
            {
                return Forbid();
            }

            // Validate comment
            if (string.IsNullOrWhiteSpace(message))
            {
                TempData["CommentError"] = "Comment cannot be empty.";

                return RedirectToAction(nameof(Details), new { id = reportId });
            }

            if (message.Length > 1000)
            {
                TempData["CommentError"] = "Comment cannot exceed 1000 characters.";

                return RedirectToAction(nameof(Details), new { id = reportId });
            }

            var comment = new Comment
            {
                ReportId = reportId,
                UserId = user.Id,
                Message = message.Trim(),
                CreatedAt = DateTime.UtcNow
            };

            _context.Comments.Add(comment);

            await _context.SaveChangesAsync();

            TempData["CommentSuccess"] = "Comment added successfully.";

            return RedirectToAction(nameof(Details), new { id = reportId });
        }
        private static string GenerateTrackingNumber()
        {
            return $"GCR-{DateTime.UtcNow:yyyyMMddHHmmss}-{Random.Shared.Next(1000, 9999)}";
        }
    }
}